genomizer/genomizer-server

src/ServerMain.java
I've extracted commandline argument parsing and loading settings.cfg file into more manageable chunks, and documented them.
=> Code cleanup ServerMain.java

src/ServerMain.java, src/server/Doorman.java
This is a simple clean-up branch. Someone should probably verify I havn't changed some behavior by accident, but I don't believe I have.
=> Clean up server main

src/ServerMain.java, src/server/Doorman.java, src/server/ServerSettings.java
Output and error logging refactoring
=> Logging refactoring

src/transfer/HTTPURLUpload.java, test/database/test/TestInitializer.java, test/database/test/unittests/TimeTest.java
Merge server develop and master in preparation of new branching model.
=> Server develop

.gitignore, settings.cfg
Restored the settings file as agreed upon.
=> Restore settings cfg

sql/add_test_tuples.sql, sql/genomizer_database_tables.sql, test/conversion/test/GenomeReleaseConverterTest.java, test/conversion/test/ProfileDataConverterTest.java, test/database/test/TestInitializer.java, test/database/test/unittests/DatabaseAccessorThreadTests.java, test/database/test/unittests/GetFileTupleTest.java, test/database/test/unittests/SearchDatabaseTests.java
Fixes #136. All tests now pass on Travis (except those that are disabled, see #138).
=> Test suite fixes

build.xml, src/SecureServerMain.java, src/server/SecureDoorman.java
Updated the build script to support both types of server.
Also implemented the Https server with the exception messages.
=> Https server continued

src/process/Executor.java
Some refactors and file moving made filesystem independent.
=> Process refactor

src/database/DatabaseAccessor.java, src/database/subClasses/AnnotationMethods.java, src/database/subClasses/ExperimentMethods.java, src/database/subClasses/GenomeMethods.java
Some minor fixes to malformed javadoc in the database package.
=> DB JavaDoc fixes

build.xml
Fixes "ant build" and "ant jar" failing.
=> Fixed broken build.xml entries: "lib" -> "external-libs"

src/database/FilePathGenerator.java
=> Hotfix permissions

src/command/CommandHandler.java
Made most of the method calls in the case-switch part of CommandHandler.java into oneliners.
=> minor_refactoring_of_commandhandler

src/command/GetExperimentCommand.java, src/response/AddAnnotationFieldResponse.java, src/response/AddFileToExperimentResponse.java, src/response/AddGenomeReleaseResponse.java, src/response/AnnotationInformation.java, src/response/DeleteGenomeReleaseResponse.java, src/response/DownloadResponse.java, src/response/ErrorResponse.java, src/response/FileInformation.java, src/response/GetAnnotationInformationResponse.java, src/response/GetExperimentResponse.java, src/response/GetGenomeReleaseResponse.java, src/response/GetProcessStatusResponse.java, src/response/LoginResponse.java, src/response/MinimalResponse.java, src/response/ProcessResponse.java, src/response/Response.java, src/response/SearchResponse.java, src/response/StatusCode.java, test/response/test/DownloadResponseTest.java
Added comments to the classes in the response folder.
Also cleaned up the code a bit.
=> Bl refactor response

src/command/GetProcessStatusCommand.java, src/response/GetProcessStatusResponse.java, src/server/WorkHandler.java, src/server/WorkPool.java, test/command/test/GetProcessStatusCommandTest.java
Changed the interface of the workpool and the dependencies.
=> Work pool refac

src/command/Command.java, test/command/test/AddFileToExperimentCommandTest.java
Fixed regex mistake in hasInvalidCharacters used in validate for commands. Now allows the character . for file-endings
=> Fixed regex mistake

src/server/Doorman.java
=> Upload/download: implement authorization.

src/command/AddAnnotationFieldCommand.java, src/command/AddAnnotationValueCommand.java, src/command/AddExperimentCommand.java, src/command/AddFileToExperimentCommand.java, src/command/AddGenomeReleaseCommand.java, src/command/ChangeUserPasswordCommand.java, src/command/Command.java, src/command/DeleteAnnotationFieldCommand.java, src/command/DeleteAnnotationValueCommand.java, src/command/DeleteExperimentCommand.java, src/command/DeleteFileFromExperimentCommand.java, src/command/DeleteGenomeReleaseCommand.java, src/command/EditAnnotationFieldCommand.java, src/command/EditAnnotationValueCommand.java, src/command/GetExperimentCommand.java, src/command/GetFileFromExperimentCommand.java, src/command/GetGenomeReleaseSpeciesCommand.java, src/command/LoginCommand.java, src/command/LogoutCommand.java, src/command/ProcessCommand.java, src/command/SearchForExperimentsCommand.java, test/command/test/AddFileToExperimentCommandTest.java, test/command/test/ProcessCommandTest.java
Allows all characters in metadata.
=> Proper regex fix

sql/add_test_tuples.sql, sql/genomizer_database_tables.sql, src/command/AddFileToExperimentCommand.java, src/command/AddGenomeReleaseCommand.java, src/command/Command.java, src/database/DatabaseAccessor.java, src/database/subClasses/GenomeMethods.java, src/transfer/UploadHandler.java, test/command/test/AddGenomeReleaseCommandTest.java, test/database/test/unittests/ChainFilesTest.java, test/database/test/unittests/DatabaseAccessorThreadTests.java, test/database/test/unittests/FileTableTests.java, test/database/test/unittests/GenomeReleaseTableTests.java, test/database/test/unittests/MockUserTests.java
=> Implement MD5 check for genome release and chain files.

src/database/DatabaseAccessor.java, src/database/containers/ChainFile.java, src/database/containers/ChainFiles.java, src/database/containers/FileTuple.java, src/database/containers/GenomeFile.java, src/database/containers/HasCheckSumMD5.java, src/database/subClasses/FileMethods.java, src/database/subClasses/GenomeMethods.java, src/transfer/UploadHandler.java, test/database/test/unittests/ChainFilesTest.java
=> Calculate and update the checksum when the client hasn't sent it.

src/process/RawToProfileConverter.java
The server becomes very slow and unresponsive when processing runs, this fixes that issue.
=> Fixes server freezing due to load issues

src/command/ConvertFileCommand.java, test/command/test/ConvertFileCommandTest.java
=> Convertfileformat

src/conversion/ConversionHandler.java
=> Conversion handler returns file tuple instead of string!

src/command/CommandClasses.java, src/command/URILength.java, src/command/UserRights.java, src/command/admin/DeleteUserCommand.java, src/command/admin/PostUserCommand.java, src/command/admin/PutUserAdminCommand.java, src/command/user/PutUserCommand.java, test/command/test/DeleteUserCommandTest.java, test/command/test/PostUserCommandTest.java, test/command/test/PutUserAdminCommandTest.java, test/command/test/PutUserCommandTest.java
fixed edit user both for admin and users
=> fixed edit user both for admin and users

src/server/RequestHandler.java, src/transfer/Util.java
Removed duplicate debugging logging.
=> Removed duplicate debugging logging.

src/command/connection/PostLoginCommand.java
=> refactored PostLoginCommand

src/server/Doorman.java
Added a /process context in doorman, to be used with a GET /process request.
=> Added a /process context in doorman, to be used with a GET /process request.

src/command/experiment/GetExperimentCommand.java, src/response/GetExperimentResponse.java, test/command/test/GetExperimentCommandTest.java
=> Refactoring GetExperiment

src/database/FileValidator.java, src/transfer/Util.java, test/transfer/test/UtilTest.java
=> Add a function for validating relative paths.

src/command/process/CancelProcessCommand.java, src/command/search/SearchCommand.java
=> Fix search.

src/command/Command.java, src/command/annotation/PostAnnotationFieldCommand.java, src/command/annotation/PostAnnotationValueCommand.java, src/command/annotation/PutAnnotationValueCommand.java, src/command/experiment/PostExperimentCommand.java
Now checks if all the forced values in the database are present, and that no dropdown-value is named "freetext" due to causing errors in the client.
=> Annotation forced check

resources/ratio_calc_wrapper.sh, resources/ratio_calculator_v2.pl
The ratio calculation script. I've written an expect script for easier use.
=> Added scripts for ratio calculation. The expect script is for ease-of-use.

src/command/CommandClasses.java, src/command/process/GetProcessDummyCommand.java, src/server/Doorman.java
Added a dummy for GET /process at GET /process/dummy so that clients can request data until properly implemented.
=> Dummy process

src/command/file/GetFileCommand.java, src/server/RequestHandler.java, test/command/test/GetFileCommandTest.java
=> Get file by id command branch

src/ServerMain.java, src/command/CommandClasses.java, src/command/user/PutUserPasswordCommand.java, src/server/Doorman.java
Structured the command classes a bit better to match API documentation.
=> Bl refactor api

src/command/connection/PostLoginCommand.java
new validateexceptions when username or password is too long
=> new validateexceptions for login

src/database/subClasses/GenomeMethods.java
fix multiple genome release upload
=> changed query

resources/smooth_v4.pl, resources/smooth_wrapper.sh, src/server/ProcessHandler.java
Simple bugfix for very fast processing, and wrapper script for smoothing.
=> Fix processing bug along with wrapper script

src/command/search/SearchCommand.java, src/server/RequestHandler.java
The title is self-explanatory. "fixes #220"
=> Added the ability to search using an empty string.

sql/add_test_tuples.sql, test/command/test/PutExperimentCommandTest.java, test/database/test/unittests/AnnotationRequiredDefaultTest.java, test/database/test/unittests/GetAnnotationObjectTest.java, test/database/test/unittests/SearchDatabaseTests.java, test/server/test/dummies/ClientDummy.java, test/server/test/dummies/Experiment.java
Removed whitespaces and added emptystring values to annotation choises
=> Test tuples annotation fix

src/command/search/SearchCommand.java
Small fix for the IOException.
=> Search query fix

postman-test/Genomizer.json.postman_collection, src/authentication/Authenticate.java, src/authentication/InactiveUuidsRemover.java, src/authentication/LoginAttempt.java, src/command/Command.java, src/command/connection/DeleteLoginCommand.java, src/command/connection/IsTokenValidCommand.java, src/command/experiment/DeleteExperimentCommand.java, src/command/search/SearchCommand.java, src/command/user/PutUserCommand.java, src/server/RequestHandler.java, test/command/test/DeleteLoginCommandTest.java, test/command/test/PostAnnotationFieldCommandTest.java, test/command/test/PostAnnotationValueCommandTest.java, test/command/test/PostExperimentCommandTest.java, test/command/test/PostFileCommandTest.java, test/command/test/PostUserCommandTest.java, test/command/test/PutExperimentCommandTest.java, test/server/test/CreateProcessCommandTest.java
=> Make IsTokenValidCommand work again.

src/command/Command.java
Changed response message when validation fails because of incorrect string length.
=> validateexception changed in validate

resources/readsgff_to_allnucsgr_v1.pl, resources/readsgff_to_allnucsgr_v1.sh, resources/sam_to_readsgff_v1.pl, resources/sam_to_readsgff_v1.sh, src/process/Executor.java, src/process/RawToProfileConverter.java, src/server/ProcessHandler.java
Ummm.. Don't know how Github thinks I'm amritb from Mumbai, but guess any magic can happen when you're working in a virtual environment.
=> Fixing processing pipeline

src/command/file/PutFileCommand.java, src/response/HttpStatusCode.java, src/response/ProcessResponse.java, src/response/Response.java, src/server/ProcessHandler.java, test/server/test/dummies/PutProcessCommandMock.java
=> Add a 'getMessage' method to Response.

src/process/Picard.java
=> Fixes line which exceeds 80 cols

sql/add_test_tuples.sql, sql/genomizer_database_tables.sql, src/database/DatabaseAccessor.java, src/database/containers/FileTuple.java, src/database/subClasses/FileMethods.java, src/response/FileInformation.java, src/transfer/UploadHandler.java, test/database/test/unittests/GetFileTupleTest.java
Updated method: updateFileSize, should work now.
=> File size fix

src/transfer/Util.java
Minor fix to allow empty strings in a query.
=> Changed how URI formatting is handled

sql/add_test_tuples.sql, src/database/DatabaseAccessor.java, src/database/subClasses/FileMethods.java, src/transfer/Util.java, test/database/test/unittests/MockUserTests.java
want this so that our file systems is in sync
=> Moving of test files

src/transfer/UploadHandler.java
Returns response earlier. Disabled MD5 checksum checking. Returns an error if no files were received.
Fixes #366.
=> File upload fix

src/database/DatabaseAccessor.java, src/database/subClasses/FileMethods.java, test/database/test/unittests/MockUserTests.java
Adds file size to processed files
=> From now on processed files will have a filesize (I hope)

src/command/process/SmoothingProcessCommand.java, src/process/Smooth.java
added implementation of processCommand:smooth
=> implementation of processCommand:smooth

src/database/DatabaseAccessor.java, src/database/subClasses/FileMethods.java, src/database/subClasses/GenomeMethods.java, src/transfer/UploadHandler.java
=> Remove 'In Progress' tuples if upload is interrupted.

src/database/DatabaseAccessor.java, src/database/subClasses/ExperimentMethods.java, test/database/test/unittests/UpdateExperimentTest.java
Implemented method to update experiment with many annotations (as single transaction).
=> Transaction exp updates

src/database/subClasses/UserMethods.java
Fix problems with update user settings
=> Fix update user

src/database/subClasses/UserMethods.java
Reverts genomizer/genomizer-server#390
=> Revert "Fix update user"

src/database/subClasses/UserMethods.java
Update user settings now works
=> Added space between lines in sql query

src/command/file/GetFileCommand.java
Added a case to check if the response from the database was null. If so an error response is returned.
=> GetFileHotfix

src/command/admin/DeleteAdminUserCommand.java, src/command/admin/PutAdminUserCommand.java, src/command/file/GetFileCommand.java
The new restrictions is to ensure that the last admin account can never be destroyed or deleted.
=> AdminCommandsModification

src/command/process/ProcessCommands.java, src/command/process/PutProcessCommand.java, src/server/ProcessPool.java, test/server/test/ProcessPoolTest.java
New validate check + some small fixes.
=> Improvements to refactored process pool 

src/command/file/GetFileCommand.java, src/command/process/ProcessCommand.java, src/command/process/RatioProcessCommand.java, src/command/process/RawToProfProcessCommand.java, src/command/process/StepProcessCommand.java, test/command/test/process/RatioProcessCommandTest.java
Worked on implementation, refactored, commented etc
=> Worked on implementation of processCommands

src/authentication/Authenticate.java
=> Hot fix for the date checking for the logins.

src/command/experiment/PostExperimentCommand.java
Changed the PostExperimentCommand to utilize the getAllForcedAnnotations() function in the DatabaseAccessor.
=> PostExperimentRefactor

src/command/Command.java
Changed some comments in the Command class.
=> MinorCommandChanges

src/command/process/ProcessCommands.java, src/command/process/RawToProfProcessCommand.java, src/command/process/SmoothingProcessCommand.java
Added handling of information for errors during processing. Requires informative messages from the processing steps.
=> handling of more info for errors during processing

src/conversion/ConversionHandler.java
Added a filesize for converted profiledata, also renamed variable to be less confusing
=> Adds a filesize to converted profile files

test/process/test/SmoothTest.java
Just needed to tweak parameters a little.
=> Check that smoothing produces non-empty files.

src/command/connection/PostLoginCommand.java, test/command/test/process/RawToProfProcessCommandTest.java
=> hotfix login error messages

src/command/CommandClasses.java, src/command/UserRights.java
Also did some reordering to make it easier to find all commands.
Fixes #438
=> Added the user rights for the remove processes command.

src/command/experiment/PostExperimentCommand.java
Was being removed when an experiment with the same name already existed.
=> Fix problem with adding new experiment. 

src/transfer/UploadHandler.java
=> Hotfix for file upload.

src/transfer/UploadHandler.java
Reverts genomizer/genomizer-server#458
=> Revert "Hotfix for file upload."

resources/ratio/ratio_calc_wrapper.sh, settings.cfg, src/process/Ratio.java
=> Ratio calc working

.travis.yml
Don't merge before the test passes on Travis.
=> travis.yml: Use container-based infrastructure.

README.md, src/command/process/RawToProfProcessCommand.java, src/process/RawToProfileConverter.java, src/process/Step.java, src/smoothing/SmoothingAndStep.java, test/process/test/RawToProfileTest.java, test/process/test/StepTest.java
All the requested functionality is fully functional. Should be ready for delivery. @23Skidoo can you merge if it's ready and then launch it to the production server?
=> Final delivery 2015

src/command/process/RawToProfProcessCommand.java, src/process/Pyicos.java, src/process/RawToProfileConverter.java, test/process/test/PyicosTest.java, test/process/test/RawToProfileTest.java
Added support for optional extension of reads. No longer done automatically.
=> Optional extend reads

src/command/process/RawToProfProcessCommand.java, src/process/Pyicos.java, src/process/RawToProfileConverter.java, test/process/test/PyicosTest.java, test/process/test/RawToProfileTest.java
Added support for optional extension of reads.
=> Optional extension of reads
